---

- name: Create /usr/share/java directory
  file:
    path: /usr/share/java
    state: directory
    mode: 0755

- name: Copy MySQL Connector/J jar file to correct location
  copy:
    src: "{{ mysql_connector_local_path }}"
    dest: /usr/share/java/mysql-connector-java.jar
    mode: 0644
