---

- fail:
    msg: |
      Requires...
      task_args.hs2_host or task_args.cluster_name
      task_args.ddl
      task_args.kerberos
      task_args.tls

      Optional...
      task_args.run_as
      task_args.hs2_port (default 10000)
      task_args.delegate_host
      task_args.truststore
      task_args.truststore_password
  when: >
    (task_args.hs2_host is not defined
     and task_args.cluster_name is not defined
     and postinstall_default_cluster is not defined)
    or task_args.ddl is not defined
    or task_args.kerberos is not defined
    or task_args.tls is not defined

- set_fact:
    host: >-
      {{
      ((definition.clusters
      | find_clusters(name=task_args.cluster_name | default(postinstall_default_cluster))
      | first
      | cluster_service_role_hosts(hostvars, 'HIVE_ON_TEZ', ['HIVESERVER2']))
      + (definition.clusters
      | find_clusters(name=task_args.cluster_name | default(postinstall_default_cluster))
      | first
      | cluster_service_role_hosts(hostvars, 'HIVE', ['HIVESERVER2'])))
      | first
      }}
  when: task_args.cluster_name is defined or postinstall_default_cluster is defined

- set_fact:
    host: "{{ task_args.hs2_host }}"
  when: task_args.hs2_host is defined

- set_fact:
    local_user: "{{ task_args.local_user | default(postinstall_local_user) }}"
    hs2: "{{ host }}:{{ task_args.hs2_port | default(10000) }}"

- set_fact:
    identity: "{{ postinstall_user_prefix ~ task_args.run_as }}"
  when: task_args.run_as is defined

- set_fact:
    identity: "hive"
  when: task_args.run_as is not defined

- name: Initialize Hive
  auth_shell:
    cmd: "{{ lookup('template', 'hive.j2') }}"
    cm_host: "{{ cloudera_manager_host }}"
    cm_port: "{{ cloudera_manager_port }}"
    cm_user: "admin"
    cm_pass: "{{ cloudera_manager_api_password }}"
    fallback: "hive"
    identity: "{{ identity }}"
    host: "{{ host }}"
    set_hadoop_env_on_failure: true
  delegate_to: "{{ task_args.delegate_host | default(host) }}"
  run_once: true
  become: true
  become_user: "{{ local_user }}"
  register: hive_comm

- debug:
    var: hive_comm
  delegate_to: "{{ task_args.delegate_host | default(host) }}"
  run_once: true
