---

- name: Include variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != "Debian"

- name: Include variables
  include_vars:
    file: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "Debian"

- name: Install rng-tools package
  package:
    name: "{{ __rngd_package_name }}"
    state: present
    update_cache: yes
  when: ansible_virtualization_role == 'guest'

- name: Configure rngd to use /dev/urandom (RHEL/CentOS 7)
  template:
    src: rngd.service.j2
    dest: /etc/systemd/system/rngd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rngd
  when:
    - ansible_virtualization_role == 'guest'
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int >= 7

- name: Configure rngd to use /dev/urandom (Ubuntu)
  debug:
    msg: TODO
  when:
    - ansible_virtualization_role == 'guest'
    - ansible_distribution == 'Ubuntu'

- name: Enable and start rngd
  service:
    name: "{{ __rngd_service_name }}"
    state: started
    enabled: yes
  when: ansible_virtualization_role == 'guest'
