---

- name: Include variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Install KRB5 server
  package:
    name: "{{ krb5_packages }}"
    state: present

- name: Set kdc.conf
  template:
    src: kdc.conf.j2
    dest: "{{ krb5_kdc_state_directory }}/kdc.conf"
    backup: yes

- name: Create KDC database
  command: "/usr/sbin/kdb5_util create -s -P {{ krb5_kdc_master_password }}"
  args:
    creates: "{{ krb5_kdc_state_directory }}/principal"

- name: Set kadm5.acl
  template:
    src: kadm5.acl.j2
    dest: "{{ krb5_kdc_state_directory }}/kadm5.acl"
    backup: yes

- name: Create Cloudera Manager admin principal
  command: /usr/sbin/kadmin.local -q "addprinc -pw {{ krb5_kdc_admin_password }} {{ krb5_kdc_admin_user }}"

- name: Start Kerberos KDC
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ krb5_services }}"
