---
postgresql_version: "{{ database_version }}"
postgresql_enablerepo: pgdg
postgresql_data_dir: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_bin_path: /usr/pgsql-{{ postgresql_version }}/bin
postgresql_config_path: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_daemon: postgresql-{{ postgresql_version }}.service
postgresql_packages:
  - postgresql{{ postgresql_version | regex_replace('\.','') }}
  - postgresql{{ postgresql_version | regex_replace('\.','') }}-server
  - postgresql{{ postgresql_version | regex_replace('\.','') }}-libs
  - postgresql{{ postgresql_version | regex_replace('\.','') }}-contrib
  - postgresql{{ postgresql_version | regex_replace('\.','') }}-devel
postgresql_python_library: python-psycopg2
