---

- name: Setup Ranger policies
  include_tasks: cluster_setup_ranger.yml
  run_once: true
  loop: "{{ definition.clusters }}"
  loop_control:
    loop_var: cluster
    label: "{{ cluster.name }}"
  vars:
    policies: "{{ combined_postinstall_policies }}"
  when:
    - "'RANGER' in cluster.services | default([])"

- name: Setup Ranger policies (keyadmin)
  include_tasks: cluster_setup_ranger.yml
  run_once: true
  loop: "{{ definition.clusters }}"
  loop_control:
    loop_var: cluster
    label: "{{ cluster.name }}"
  vars:
    use_ranger_keyadmin: True
    policies: "{{ combined_postinstall_keyadmin_policies }}"
  when:
    - "'RANGER' in cluster.services | default([])"
    - cluster.security.hdfs_encryption | default(False)
