---

- name: Import KDC admin credentials
  uri:
    url: "{{ cloudera_manager_api }}/cm/commands/importAdminCredentials?username={{ krb5_kdc_admin_user }}&password={{ krb5_kdc_admin_password }}"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ cloudera_manager_api_user }}"
    password: "{{ cloudera_manager_api_password }}"
    return_content: yes
  register: response
  when: krb5_kdc_admin_user is defined

- name: Wait for KDC admin credentials import to complete
  uri:
    url: "{{ cloudera_manager_api }}/commands/{{ response.json.id }}"
    body_format: json
    force_basic_auth: yes
    user: "{{ cloudera_manager_api_user }}"
    password: "{{ cloudera_manager_api_password }}"
    return_content: yes
  register: result
  until: not result.json.active
  retries: 30
  delay: 10
  when: krb5_kdc_admin_user is defined
  failed_when: result.json.success is defined and not result.json.success
